apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-wuqy
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0070-tenant/tkrw-pr712-0075-0070-app/devfile-sample-wuqy@sha256:3d66e8a3e4f9d9f000a68d20c54f99c1895575ed5ceecd003f7b0b0f4be6ee60
        name: my-nodejs
        resources: {}
status: {}
